title: MSPMesh Wiki
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true
aux_links:
  GitHub: https://github.com/MSPMesh/MSPMesh.github.io
  Discord: https://discord.com/invite/xfyDHKUff9
  Main Website: https://mspmesh.org/